# Generated by Django 5.2.16 on 2026-08-03 05:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0004_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('marks', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='subjects.chapter')),
            ],
            options={
                'ordering': ['chapter', 'created_at'],
            },
        ),
    ]
