# Generated by Django 5.2.16 on 2026-08-05 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_is_multiple_answer_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['chapter__subject__exam__name', 'chapter__subject__name', 'chapter__name']},
        ),
    ]
