# Generated by Django 5.2.16 on 2026-08-06 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('questions', '0003_alter_question_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='assessment.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='questions.question')),
            ],
            options={
                'ordering': ['assessment', 'display_order'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'question'), name='unique_question_per_assessment'), models.UniqueConstraint(fields=('assessment', 'display_order'), name='unique_display_order_per_assessment')],
            },
        ),
    ]
