# Generated by Django 5.2.16 on 2026-09-15 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('subjects', '0003_alter_program_institute_studentprogramenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['program', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='assessment',
            name='unique_assessment_name_per_teacher_per_subject',
        ),
        migrations.AddField(
            model_name='assessment',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='subjects.program'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('created_by', 'program', 'name'), name='unique_assessment_name_per_teacher_per_program'),
        ),
    ]
