# Generated by Django 5.2.16 on 2026-08-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_assessmentattempt_attemptquestion_studentanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
