# Generated by Django 5.2.16 on 2026-09-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_auto_20260915_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='subject',
        ),
    ]
