# Generated by Django 5.2.16 on 2026-08-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['name'], 'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
    ]
