# Generated by Django 5.2.16 on 2026-08-25 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherassignment',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='teacherassignment',
            name='unique_teacher_assignment_per_subject',
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='subjects.chapter'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='subjects.subject'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('subject__isnull', False), ('chapter__isnull', True)), models.Q(('subject__isnull', True), ('chapter__isnull', False)), _connector='OR'), name='teacher_assignment_subject_or_chapter'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('subject__isnull', False)), fields=('teacher', 'subject'), name='unique_teacher_subject_assignment'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('chapter__isnull', False)), fields=('teacher', 'chapter'), name='unique_teacher_chapter_assignment'),
        ),
    ]
