# Generated by Django 5.2.16 on 2026-09-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_program_institute_studentprogramenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='access',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('INSTITUTE', 'Institute'), ('PRIVATE', 'Private')], default='INSTITUTE', max_length=20),
        ),
    ]
